version: '3.7'
services:
  moodle:
    build: .
    ports:
      - "8080:80"
    volumes:
      - moodledata:/var/www/moodledata
    depends_on:
      - db
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodleuser
      MYSQL_PASSWORD: moodlepassword
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  moodledata:
  dbdata: