version: '3'
services:
  nginx:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "80:80"
  microservice1:
    image: aidro/warpnet-srechallenge
    ports:
      - "5050"
  microservice2:
    image: aidro/warpnet-srechallenge
    ports:
      - "5050"