events {}
http {
    upstream backend {
        server microservice1:5050;
        server microservice2:5050;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend;
        }
    }
}